### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by BenjaminEHowe** [schnerring/cloudflare-pages-branch-alias-action#191]
Please update this action to use Node.js 20. I _think_ you just need to create a new release version as [it looks like you're already using Node.js 20](https://github.com/schnerring/cloudflare-pages-branch-alias-action/blob/0c051f35e92c4a656e34023406f2639be2a5fd2f/package.json#L24).

**Comment by schnerring** [comment]
[I released v1.2.0.](https://github.com/schnerring/cloudflare-pages-branch-alias-action/releases/tag/v1.2.0) Sorry for the delay!
